import pickle
import numpy as np
from pathlib import Path
import matplotlib.pyplot as plt


def load_qdspy_movie(pickle_path):
    """ Load a pickle file generated by the record-stimulus-as-movie function
        of QDSpy and returns it as a numpy.ndarray
    """
    print(f"Loading pickle file from: {pickle_path}")
    with open(pickle_path, 'rb') as f:
        data = pickle.load(f)
    
    if isinstance(data, np.ndarray):
        image_array = data
        print("Done.")
    else:
        image_array = None
        print("Error: File does not contain a simple numpy array as expected.")    
    
    return image_array


def calc_intensity_trace(
        _mov: np.array, _p: dict,
        _range_s: list =[0,-1], 
        _field_xy_um: list =[0,0], _field_size_um: list =[150,150],
        _plot: bool = False
    ):
    """ Calculate intensity traces (mean and cumulative) for a field 
        (~ recording field plus surround) within a movie
    """
    pix_size_um = _p["pix_size_um"]
    mov_dx_um = _p["mov_dxy_um"][0]
    mov_dy_um = _p["mov_dxy_um"][1]
    dt_fr_s = _p["dt_fr_s"]
    nCh = _p["nCh"]

    # Calculate field in pixel indices
    ix = int((_field_xy_um[0] +mov_dx_um /2) /pix_size_um)
    iy = int((_field_xy_um[1] +mov_dy_um /2) /pix_size_um)
    ix0 = ix -int(_field_size_um[0] /2 /pix_size_um)
    ix1 = ix +int(_field_size_um[0] /2 /pix_size_um)
    iy0 = iy -int(_field_size_um[1] /2 /pix_size_um)
    iy1 = iy +int(_field_size_um[1] /2 /pix_size_um)
    print(f"Crop movie to pixels x={ix0}..{ix1}, y={iy0}..{iy1}")

    # Crop movie to a field (~ recording field plus some surround)
    n_fr, _, _, _ = _mov.shape
    _range_s[1] = n_fr *dt_fr_s if _range_s[1] == -1 else _range_s[1]
    it0 = int(max(0, _range_s[0] /dt_fr_s))
    it1 = int(min(n_fr, _range_s[1] /dt_fr_s))
    print(f"Use movie snippet from {_range_s[0]}..{_range_s[1]}s ({it0}..{it1})")
    mov_range = _mov[it0:it1]
    mov_cropped = mov_range[:,ix0:ix1,iy0:iy1,:]

    # Calculate mean intensity in cropped frame over time and clumulative intensity
    intens = np.mean(mov_cropped, axis=(1, 2))
    intens_cumul = np.cumsum(intens, axis=0)
    time_s = np.arange(intens.shape[0]) * dt_fr_s

    if _plot:
        # Plot both traces
        fig, axes = plt.subplots(2, 1, figsize=(12, 8), sharex=True)
        colors = ['violet', 'green', 'blue']  # for channels 0, 1, 2

        # Mean intensity trace
        for ch in range(nCh):
            axes[0].plot(time_s, intens[:, ch], color=colors[ch], label=f'Ch {ch}')
        axes[0].set_ylabel('Mean Intensity')
        axes[0].set_title('Mean Intensity Over Time')
        axes[0].legend()
        axes[0].grid(True)

        # Cumulative intensity trace
        for ch in range(nCh):
            axes[1].plot(time_s, intens_cumul[:, ch], color=colors[ch], label=f'Ch {ch}')
        axes[1].set_xlabel('t [s]')
        axes[1].set_ylabel('Cumulative Intensity')
        axes[1].set_title('Cumulative Intensity Over Time')
        axes[1].legend()
        axes[1].grid(True)

        plt.tight_layout()
        plt.show()

    return intens, intens_cumul   


def flatten_movie(_mov :np.array, _p: dict, _range_s: list =[0,-1], _plot: bool =False):
    """ Returns the flattened movie within the given range with 
        all intensity values summed up.
    """
    n_fr, dx, dy, nCh = _mov.shape
    dt_fr_s = _p["dt_fr_s"]
    
    # Determine range from time window
    _range_s[1] = n_fr *dt_fr_s if _range_s[1] == -1 else _range_s[1]
    it0 = int(max(0, _range_s[0] /dt_fr_s))
    it1 = int(min(n_fr, _range_s[1] /dt_fr_s))

    # Flatten
    mov_flat = np.zeros((dx,dy,nCh), dtype=np.float64) 
    mov_range = _mov[it0:it1]
    mov_flat = np.sum(mov_range, axis=0, dtype=np.float64)

    if _plot:
        # Show flattened movies
        mov_flat_norm = mov_flat /mov_flat.max() 
        vmin = mov_flat_norm.min()
        vmax = mov_flat_norm.max()
        fig, axes = plt.subplots(1, nCh, figsize=(12, 3))
        for ch in range(nCh):
            axes[ch].imshow(mov_flat_norm[:,:,ch], cmap='gray', vmin=vmin, vmax=vmax)
            axes[ch].axis('off')
        plt.tight_layout()
        plt.show()

    return mov_flat